
//AUTOGENERATED FILE: DO NOT EDIT
#include "TestMINXProject.h"
using namespace MINX_TESTMINXPROJECT;
int main(int argc, char ** argv)
{
	TestMINXProject * game = new TestMINXProject();
	game->Run();
	exit(0);
}
