
//AUTOGENERATED FILE: DO NOT EDIT
#include "MINX/Game.h"
#include "MINX/GameTime.h"
#include "MINX/Input/Keyboard.h"
#ifndef TESTMINXPROJECT_H_
#define TESTMINXPROJECT_H_

using namespace MINX;

namespace MINX_TESTMINXPROJECT
{
	class TestMINXProject : public Game
	{
		public:
			TestMINXProject();
			void Initialize();
			void LoadContent();
			void UnloadContent();
			void Update(GameTime * gameTime);
			void Draw(GameTime * gameTime);
	};
}

#endif
